# Generated by Django 4.2.9 on 2025-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_receipt_issued_at_alter_receipt_receipt_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
