# Generated by Django 5.1.6 on 2025-05-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_quotation_valid_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceservice",
            name="price_at_time",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="payments.invoice",
            ),
        ),
    ]
