# Generated by Django 5.1.6 on 2025-05-19 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_invoiceservice_price_at_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.invoice",
            ),
        ),
    ]
