# Generated by Django 5.1.6 on 2025-06-11 13:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_receipt_patient_alter_invoice_total_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="price_at_time",
        ),
        migrations.AddField(
            model_name="receipt",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price of the item at the time of receipt creation.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the item at the time of receipt creation.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
