# Generated by Django 5.1.6 on 2025-02-12 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('available_days', models.CharField(max_length=200)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_dentist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
