# Generated by Django 5.1.6 on 2025-02-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_service_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dentist',
            options={'verbose_name': 'Dentist', 'verbose_name_plural': 'Dentists'},
        ),
    ]
