# Generated by Django 5.1.6 on 2025-03-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_dentist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
