# Generated by Django 5.1.6 on 2025-05-02 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0007_alter_diagnosis_appointment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
