# Generated by Django 5.1.6 on 2025-06-11 14:13

import django.core.validators
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0009_alter_service_price"),
    ]

    operations = [
        # Temporarily allow NULL values
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                null=True,  # Allow NULL temporarily
                validators=[MinValueValidator(Decimal('0.01'))],
                help_text="Price of the service."
            ),
        ),
    ]