# Generated by Django 5.1.6 on 2025-05-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("IN", "Stock In"),
                    ("OUT", "Stock Out"),
                    ("ADJUST", "Adjustment"),
                ],
                max_length=10,
            ),
        ),
    ]
