from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('app/', views.app_login, name='app'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('patients', views.PatientsPage, name='patients'),
    path('create-patient', views.CreatePatient, name='create-patient'),
    path('appointments', views.AppointmentsPage, name='appointments'),
    path('create_user/', views.create_user, name='create_user'),
    path('register/dentist/', views.create_user, name='create_user'),
    path('register/staff/', views.create_user, name='create_user'),
    path('dentists', views.DentistsPage, name='dentists'),
    path('create_admin/', views.create_user, name='create_user'),
    path('create_appointment/', views.create_appointment, name='create_appointment'),
    path('walkin_appointment/', views.walk_in_appointment, name='walkin_appointment'),
    path('clear_appointment_created_flag/', views.clear_appointment_created_flag, name='clear_appointment_created_flag'),
    path('patient_details/<int:id>', views.patient_details, name='patient_details'),
    path('assign_dentist/', views.assign_dentist, name='assign_dentist'),
    path('update_patient_request/<int:patient_id>', views.update_patient_request, name='update_patient_request'),
    path('update_patient/', views.update_patient, name='update_patient'),
    path('complete_appointment/<int:appointment_id>', views.complete_appointment, name='complete_appointment'),
    path('treatment_request/<int:patient_id>/', views.treatment_request, name='treatment_request'),
    # path('delete_patient/', views.delete_patient, name='delete_patient'),
    # path('delete_appointment/', views.delete_appointment, name='delete_appointment'),
    path('treatment_diagnosis', views.treatment_diagnosis, name='treatment_diagnosis'),
    path('scheduled_appointment', views.scheduled_appointment_view, name='scheduled_appointment'),
    path('payment/<int:invoice_id>/create/', views.create_payment, name='create_payment'),
    path('invoices_list/', views.invoice_list_view, name='invoice_list'),
    path('invoice/<int:invoice_id>/details/', views.invoice_detail_view, name='invoice_details_view'),
    path('invoice/<int:invoice_id>/details/', views.invoice_details, name='invoice_details'),
    path('create_quotation/', views.create_quotation, name='create_quotation'),
    path('patient_invoice/<int:patient_id>/', views.patient_invoice, name='patient_invoice'),
    path('create_inovice_list/', views.create_invoice_list_view, name='create_invoice_list'),
    path('search_patient/', views.search_patient, name='search_patient'),
    path('quotation/<int:quotation_id>/download/', views.download_quotation_pdf, name='download_quotation_pdf'),
    path('quotation/<int:pk>/', views.quotation_detail, name='quotation_detail'),
    path('quotation_list/', views.quotation_list, name='quotation_list'),
    path('create_quotation_list/', views.create_quotation_list, name='create_quotation_list'),
    path('exist_patient_appointment/<int:patient_id>/', views.exist_patient_appointment, name='exist_patient_appointment'),
    path('turn_to_invoice/<int:quotation_id>/', views.turn_to_invoice, name='turn_to_invoice'),
    path('full_payment_form', views.full_payment_form, name='full_payment_form'),
    path('make_full_payment/<int:invoice_id>/', views.make_full_payment, name='make_full_payment'),
    path('full_payment/', views.full_payment, name='full_payment'),
    path('partial_payment_form/', views.partial_payment_form, name='partial_payment_form'),
    path('make_partial_payment/<int:invoice_id>/', views.make_partial_payment, name='make_partial_payment'),
    path('partial_payment', views.partial_payment, name='partial_payment'),
    path('calendar/', views.calendar_view, name='calendar'),
    path('items/', views.item_list, name='item_list'),
    path('items/<int:pk>/', views.item_detail, name='item_detail'),
    path('items/new/', views.item_create, name='item_create'),
    path('items/<int:pk>/update/', views.item_update, name='item_update'),
    path('items/<int:pk>/delete/', views.item_delete, name='item_delete'),
    path('items/<int:pk>/transactions/', views.item_transactions, name='item_transactions'),
    path('items/<int:pk>/transactions/new/', views.transaction_create, name='transaction_create'),
    path('categories/', views.category_list, name='category_list'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    # Categories
    path('categories/', views.category_list, name='category_list'),
    path('categories/new/', views.category_create, name='category_create'),
    path('categories/<int:pk>/edit/', views.category_update, name='category_update'),
    path('categories/<int:pk>/delete/', views.category_delete, name='category_delete'),
    # Suppliers
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/new/', views.supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/edit/', views.supplier_update, name='supplier_update'),
    path('suppliers/<int:pk>/delete/', views.supplier_delete, name='supplier_delete'),
    path('items/<int:pk>/transactions/new/', views.transaction_create, name='transaction_create'),
    # Receipts
    path('receipts/', views.receipt_list, name='receipt_list'),
    path('receipts/<int:pk>/', views.receipt_detail, name='receipt_detail'),
    path('invoices/<int:invoice_pk>/convert/', views.turn_into_receipt, name='turn_into_receipt'),
    path('receipts/<int:pk>/pdf/', views.generate_receipt_pdf, name='receipt_pdf'),
]